
### Before running any Compose services, make sure you have an .env file
# inside your current folder and that it has been populated with the following content:
#   GRAFANA_ADMIN_PW=<grafana-admin-pw>


### Create grafana user and assign the grafana admin password.
#  with docker-compose running, in a separate terminal window, enter the following commands:
#
#  sudo docker exec -it concordia_grafana bash -c "./setup.sh/grafana_post_run.sh"


version: '3.6'
services:  
  prometheus:
    image: prom/prometheus:latest
    container_name: concordia_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    env_file: ./.env
    restart: always
    image: grafana/grafana:latest
    container_name: concordia_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PW}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

  alertmanager:
    image: prom/alertmanager:latest
    build: ./alertmanager
    command:
      - '--config.file=/alertmanager.yml'

volumes:
  grafana_data: {}
  prometheus_data: {}

