---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the security groups should be deployed to

    DatabaseSecurityGroup:
        Description: Sets the security group to use for RDS database access
        Type: AWS::EC2::SecurityGroup::Id

    PrivateSubnet1:
        Description: A reference to the private subnet in the 1st Availability Zone
        Type: AWS::EC2::Subnet::Id

    PrivateSubnet2: 
        Description: A reference to the private subnet in the 2nd Availability Zone
        Type: AWS::EC2::Subnet::Id

    DbPassword:
        Description: The password to use for the database
        Type: String

Resources:
  dbsubnetdefaultvpc0ca0aaf8357f808b6:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Created from the RDS Management Console
      SubnetIds:
      - Ref: PrivateSubnet1
      - Ref: PrivateSubnet2

  rdsconcordia:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      AllowMajorVersionUpgrade: 'false'
      AutoMinorVersionUpgrade: 'true'
      DBInstanceClass: db.t2.medium
      Port: '5432'
      StorageType: gp2
      BackupRetentionPeriod: '7'
      MasterUsername: concordia
      MasterUserPassword: !Ref DbPassword
      PreferredBackupWindow: 03:47-04:17
      PreferredMaintenanceWindow: sun:07:14-sun:07:44
      DBName: concordia
      Engine: postgres
      EngineVersion: 9.6.6
      LicenseModel: postgresql-license
      DBSubnetGroupName:
        Ref: dbsubnetdefaultvpc0ca0aaf8357f808b6
      VPCSecurityGroups:
      - Ref: DatabaseSecurityGroup
      Tags:
      - Key: workload-type
        Value: other

Outputs:
    DatabaseHostName:
        Description : "Hostname for the relational database service"
        Value : !GetAtt rdsconcordia.Endpoint.Address
    